#nullable enable
// Создано: 2026-08-22 — Phase C (BODY-IMPL-PLAN): простые животные на тестовом полигоне.
// AnimalService — manages simple wandering animals with assembled bodies.
// Без AI-комбата, без pathfinding — только случайное блуждание в радиусе 5 тайлов.
// Body parts регистрируются в IBodyDataProvider per-entity (как у NPC).
// Источник: checkpoints/08_22_body_impl_plan.md Phase C
using System;
using System.Collections.Generic;
using CultivationGame.Core.Data;
using CultivationGame.Core.Interfaces;
using CultivationGame.Modules.Body;

namespace CultivationGame.Modules.NPC
{
    /// <summary>
    /// Manages simple wandering animals (wolf, deer, rabbit) on the test polygon.
    ///
    /// Responsibilities:
    ///  * Spawn animals with assembled Quadruped body (via IBodyFactory + IBodyDataProvider).
    ///  * Per-tick wander: pick a random walkable target within 5 tiles, step
    ///    towards it. Cooldown and speed are species-dependent.
    ///
    /// NOT a full NPC system — no soul, no AI combat, no inventory. Animals
    /// exist purely as «mobile furniture» that can be damaged/healed via
    /// IBodyDataProvider.
    ///
    /// Lifecycle:
    ///   * IStartable.Start() — fallback spawn on TestPolygon for direct
    ///     scene load (e.g. `godot scenes/GameWorld.tscn` without going
    ///     through MainMenu). Mirrors the TileModule/PlayerModule pattern.
    ///   * AnimalSpawnPhase — proper location-aware spawn during scene
    ///     assembly (called from GameSession.NewGame via RunAssembly).
    ///     Clears any existing animals first.
    ///   * ITickable.Tick() — drives wandering at 1/5/15 Hz depending on TimeSpeed.
    /// </summary>
    public sealed class AnimalService : IStartable, ITickable
    {
        // === DI dependencies ===
        private readonly IBodyDataProvider _bodyDataProvider;
        private readonly IBodyFactory _bodyFactory;
        private readonly ITileService _tileService;
        private readonly SpeciesRegistry _speciesRegistry;

        // === State ===
        private readonly List<AnimalEntity> _animals = new();

        // Deterministic RNG for wandering (separate from spawn RNG which is created per SpawnForLocation call).
        private readonly SeededRandom _wanderRng = new SeededRandom(seed: 0xC0FFEE);

        // Monotonic counter for entity IDs.
        private int _nextId = 1;

        // === Constants (species tuning) ===
        private const int WanderRadius = 5;
        private const int MaxTargetPickAttempts = 6;

        // Prime offset so animal spawns use an independent RNG stream from
        // tile/object generation (both derive from loc.Seed).
        private const int AnimalSeedOffset = 7919;

        // Minimum Chebyshev distance from player spawn (map centre) so animals
        // don't pop in on top of the player.
        private const int MinDistanceFromPlayer = 5;

        // Cap attempts to avoid infinite loop on tiny maps with no walkable tiles.
        private const int MaxSpawnAttempts = 200;

        /// <summary>
        /// Construct AnimalService. Resolved by DI; constructor injection picks
        /// up IBodyDataProvider, IBodyFactory, ITileService, SpeciesRegistry.
        /// </summary>
        public AnimalService(
            IBodyDataProvider bodyDataProvider,
            IBodyFactory bodyFactory,
            ITileService tileService,
            SpeciesRegistry speciesRegistry)
        {
            _bodyDataProvider = bodyDataProvider ?? throw new ArgumentNullException(nameof(bodyDataProvider));
            _bodyFactory = bodyFactory ?? throw new ArgumentNullException(nameof(bodyFactory));
            _tileService = tileService ?? throw new ArgumentNullException(nameof(tileService));
            _speciesRegistry = speciesRegistry ?? throw new ArgumentNullException(nameof(speciesRegistry));
        }

        // === IStartable ===

        /// <summary>
        /// Fallback spawn on TestPolygon — invoked by GameEntryPoint when the
        /// scene loads directly without going through MainMenu (e.g. CLI headless).
        /// Same pattern as TileModule.Start()/PlayerModule.Start(). If
        /// AnimalSpawnPhase later runs (via NewGame), it clears and re-spawns
        /// with the proper location.
        ///
        /// Reads map dimensions from <see cref="ITileService"/> (already
        /// generated by TileModule.Start()) and honours GODOT_MAP_SIZE env
        /// var for the large-world perf-test path.
        /// </summary>
        public void Start()
        {
            if (_animals.Count > 0) return;

            int width = _tileService.MapWidth > 0 ? _tileService.MapWidth : 50;
            int height = _tileService.MapHeight > 0 ? _tileService.MapHeight : 50;
            int seed = 12345;  // TestPolygon default
            string locId = "test_polygon";

            // Mirror TileModule.Start()'s GODOT_MAP_SIZE override for the
            // large-world perf-test path so animal spawn coords stay in-bounds.
            var envSize = System.Environment.GetEnvironmentVariable("GODOT_MAP_SIZE");
            if (!string.IsNullOrEmpty(envSize) && int.TryParse(envSize, out _))
            {
                seed = 67890;
                locId = "large_world";
            }

            SpawnForLocation(width, height, seed, locId);
        }

        // === Spawn API ===

        /// <summary>
        /// Spawn a new animal of the given species at the given tile position.
        /// Assembles a Quadruped body via BodyFactory and registers it in
        /// IBodyDataProvider under a unique entity ID.
        /// </summary>
        /// <returns>The created AnimalEntity.</returns>
        public AnimalEntity SpawnAnimal(string species, Position2D position)
        {
            if (string.IsNullOrEmpty(species))
                throw new ArgumentException("Species must be non-empty.", nameof(species));

            var data = _speciesRegistry.GetSpecies(species)
                ?? throw new ArgumentException($"Unknown species '{species}'.", nameof(species));

            var entityId = $"animal_{species}_{_nextId++}";

            var animal = new AnimalEntity(
                entityId,
                species,
                position,
                data.Morphology,
                data.Material,
                data.Size);

            // Species-specific wander tuning.
            // Rabbit: fast (2 tiles/tick), short cooldown.
            // Wolf:   normal speed, medium cooldown.
            // Deer:   normal speed, medium-long cooldown.
            switch (species)
            {
                case "rabbit":
                    animal.MoveSpeedTilesPerTick = 2;
                    break;
                case "wolf":
                case "deer":
                default:
                    animal.MoveSpeedTilesPerTick = 1;
                    break;
            }

            // Initial cooldown: 1-3 ticks (so they don't all move on tick 1).
            animal.MoveCooldownTicks = _wanderRng.Next(1, 4);

            // Assemble body parts via BodyFactory (data-driven from BodyTemplateProvider).
            // Vitality comes from SpeciesData.BaseVitality (wolf=10, deer=8, rabbit=4).
            var parts = _bodyFactory.CreateBody(data.Morphology, data.Size, data.BaseVitality);
            _bodyDataProvider.SetBodyParts(entityId, parts);

            _animals.Add(animal);
            return animal;
        }

        /// <summary>
        /// Clear all animals (used by AnimalSpawnPhase before re-spawning for
        /// a new location). Also removes their BodyParts from IBodyDataProvider.
        /// </summary>
        public void ClearAnimals()
        {
            foreach (var a in _animals)
                _bodyDataProvider.RemoveEntity(a.EntityId);
            _animals.Clear();
        }

        /// <summary>
        /// Spawn 3-5 animals at random walkable positions for the given location.
        /// Uses a SeededRandom derived from <paramref name="seed"/> + AnimalSeedOffset
        /// so the same location always produces the same set of animals. Species
        /// are picked uniformly from {wolf, deer, rabbit}. Avoids the map centre
        /// (player spawn) by MinDistanceFromPlayer.
        /// </summary>
        public int SpawnForLocation(int width, int height, int seed, string locationId)
        {
            if (width <= 0 || height <= 0)
                throw new ArgumentException($"SpawnForLocation: bad dims {width}×{height}");

            var rng = new SeededRandom(seed + AnimalSeedOffset);

            int targetCount = rng.Next(3, 6);  // 3-5 animals
            string[] speciesPool = { "wolf", "deer", "rabbit" };

            int playerX = width / 2;
            int playerY = height / 2;

            int spawned = 0;
            int attempts = 0;
            while (spawned < targetCount && attempts < MaxSpawnAttempts)
            {
                attempts++;

                // Random position within the map, leaving a 1-tile margin.
                int x = rng.Next(1, width - 1);
                int y = rng.Next(1, height - 1);

                if (!_tileService.IsWalkable(x, y))
                    continue;

                // Stay clear of the player spawn (map centre).
                int distToPlayer = Math.Max(Math.Abs(x - playerX), Math.Abs(y - playerY));
                if (distToPlayer < MinDistanceFromPlayer)
                    continue;

                var species = speciesPool[rng.Next(0, speciesPool.Length)];
                var pos = new Position2D(x, y);

                try
                {
                    var animal = SpawnAnimal(species, pos);
                    spawned++;
                    Console.WriteLine(
                        $"[AnimalSpawn] Spawned {species} #{animal.EntityId} at {pos} (body: {animal.Morphology}/{animal.Size})");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[AnimalSpawn] Failed to spawn {species} at {pos}: {ex.GetType().Name}: {ex.Message}");
                }
            }

            Console.WriteLine(
                $"[AnimalSpawn] {locationId}: spawned {spawned}/{targetCount} animals (attempts={attempts})");
            return spawned;
        }

        // === Query ===

        /// <summary>Get all animals (snapshot for renderer). Read-only view.</summary>
        public IReadOnlyList<AnimalEntity> GetAllAnimals() => _animals;

        // === ITickable ===

        /// <summary>
        /// Per-tick wander update. Called by GameEntryPoint at 1/5/15 Hz
        /// depending on TimeSpeed.
        ///
        /// Per animal:
        ///   1. If dead → skip.
        ///   2. Decrement MoveCooldownTicks. If still >0, skip.
        ///   3. If no Target (or target reached) → pick a new walkable tile
        ///      within WanderRadius. Reset cooldown (species-dependent).
        ///   4. Step MoveSpeedTilesPerTick tiles towards Target via
        ///      greedy single-tile moves (diagonal first, then orthogonal).
        /// </summary>
        public void Tick(int tickCount)
        {
            // Periodic debug log so headless tests can confirm Tick is wired.
            // First 3 ticks + every 30 after that.
            if (_animals.Count > 0 && (tickCount <= 3 || (tickCount > 0 && tickCount % 30 == 0)))
            {
                var first = _animals[0];
                Console.WriteLine(
                    $"[AnimalService] Tick #{tickCount} — {_animals.Count} animals; sample: {first.Species}#{first.EntityId} @ {first.Position}");
            }

            for (int i = 0; i < _animals.Count; i++)
            {
                var a = _animals[i];
                if (!a.IsAlive) continue;

                // Cooldown gate — wait before next action.
                if (a.MoveCooldownTicks > 0)
                {
                    a.MoveCooldownTicks--;
                    continue;
                }

                // Need a new target?
                if (a.Target is null || a.Position == a.Target.Value)
                {
                    if (!TryPickNewTarget(a))
                    {
                        // No walkable tile found — wait one tick and retry.
                        a.MoveCooldownTicks = 1;
                        continue;
                    }
                }

                // Step towards target.
                StepTowardsTarget(a);

                // If reached target, schedule next wander.
                if (a.Target is null || a.Position == a.Target.Value)
                {
                    a.Target = null;
                    a.MoveCooldownTicks = GetWanderCooldownTicks(a.Species);
                }
            }
        }

        // === Helpers ===

        /// <summary>
        /// Pick a random walkable tile within ±WanderRadius of the animal's
        /// current position. Tries MaxTargetPickAttempts random offsets;
        /// returns false if none of them are walkable.
        /// </summary>
        private bool TryPickNewTarget(AnimalEntity a)
        {
            for (int attempt = 0; attempt < MaxTargetPickAttempts; attempt++)
            {
                int dx = _wanderRng.Next(-WanderRadius, WanderRadius + 1);
                int dy = _wanderRng.Next(-WanderRadius, WanderRadius + 1);

                // Skip zero-offset (would set Target == Position immediately).
                if (dx == 0 && dy == 0) continue;

                int tx = a.Position.X + dx;
                int ty = a.Position.Y + dy;

                if (_tileService.IsWalkable(tx, ty))
                {
                    a.Target = new Position2D(tx, ty);
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Move the animal up to MoveSpeedTilesPerTick tiles towards Target.
        /// Greedy: each sub-step tries diagonal first, then horizontal,
        /// then vertical. If all three are blocked, aborts the target.
        /// </summary>
        private void StepTowardsTarget(AnimalEntity a)
        {
            if (a.Target is null) return;
            var target = a.Target.Value;

            int stepsRemaining = a.MoveSpeedTilesPerTick;
            while (stepsRemaining > 0 && a.Position != target)
            {
                int dx = Math.Sign(target.X - a.Position.X);
                int dy = Math.Sign(target.Y - a.Position.Y);

                int newX = a.Position.X + dx;
                int newY = a.Position.Y + dy;

                // Try diagonal.
                if (dx != 0 && dy != 0 && _tileService.IsWalkable(newX, newY))
                {
                    a.Position = new Position2D(newX, newY);
                }
                // Try horizontal.
                else if (dx != 0 && _tileService.IsWalkable(a.Position.X + dx, a.Position.Y))
                {
                    a.Position = new Position2D(a.Position.X + dx, a.Position.Y);
                }
                // Try vertical.
                else if (dy != 0 && _tileService.IsWalkable(a.Position.X, a.Position.Y + dy))
                {
                    a.Position = new Position2D(a.Position.X, a.Position.Y + dy);
                }
                else
                {
                    // Blocked — give up on this target.
                    a.Target = null;
                    a.MoveCooldownTicks = GetWanderCooldownTicks(a.Species);
                    return;
                }

                stepsRemaining--;
            }
        }

        /// <summary>
        /// Species-dependent cooldown in ticks between wander decisions.
        /// Rabbit (small/fast): 2-3 ticks. Wolf (predator): 3-5. Deer: 3-6.
        /// </summary>
        private int GetWanderCooldownTicks(string species)
        {
            return species switch
            {
                "rabbit" => _wanderRng.Next(2, 4),
                "wolf"   => _wanderRng.Next(3, 6),
                "deer"   => _wanderRng.Next(3, 7),
                _        => _wanderRng.Next(3, 6),
            };
        }
    }
}
